version: '2'
services:
  wordpress:
    depends_on:
      - db
    # Docker hub for wordpress: https://hub.docker.com/_/wordpress/
    # Test versions:
    #   5.3.0
    #
    image: wordpress:5.3.0
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: p4ssw0rd!
    ports:
      - 80:80
      - 443:443
    networks:
      - back
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - back
networks:
  back:
volumes:
  db_data:
